---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-config
  namespace: pyroute2-cni
data:
  frr.conf.tpl: |
    !
    service integrated-vtysh-config
    !
    $vrf_sections
    !
    router bgp 65000
     bgp router-id $router_id
     neighbor PR2 peer-group
     neighbor PR2 remote-as internal
    $peer_records
     !
     address-family ipv4 unicast
      network $router_id/32
     exit-address-family
     !
     address-family l2vpn evpn
      neighbor PR2 activate
      advertise-all-vni
      advertise-svi-ip
     exit-address-family
    exit
    !
    $vrf_router_sections
    !
    end
  vtysh.conf: |
    service integrated-vtysh-config
  daemons: |
    bgpd=yes
    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="   -A 127.0.0.1"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: pyroute2-cni
data:
  server.ini: |
    [api]
    socket_path_api = /var/run/pyroute2/api
    socket_path_fd = /var/run/pyroute2/fdpass

    [default]
    prefix = 10.244.0.0
    prefixlen = 16
    ipblocklen = 26
    l2vni = 42
    vrf = 42
    service_vrf_max = 512
    srv6end = fc00:100:$host_order::$vrf_table:a
    srv6endDT4 = fc00:100:$host_order::$vrf_table:b
    srv6local = fc00:200:1:$host_order::5

    [bgp]
    rr_mode = mesh
