apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: pyroute2-cni
    name: pyroute2-cni
    k8s-app: pyroute2-cni
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
  name: pyroute2-cni
