---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: pyroute2-cni
    name: pyroute2-cni
    k8s-app: pyroute2-cni
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
  name: pyroute2-cni
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pyroute2-cni-sa
  namespace: pyroute2-cni
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pyroute2-cni-clusterrole
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pyroute2-cni-binding
subjects:
  - kind: ServiceAccount
    name: pyroute2-cni-sa
    namespace: pyroute2-cni
roleRef:
  kind: ClusterRole
  name: pyroute2-cni-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: pyroute2-cni
data:
  server.ini: |
    [api]
    socket_path_api = /var/run/pyroute2/api
    socket_path_fd = /var/run/pyroute2/fdpass

    [network]
    host_if = enp1s0

    [default]
    prefix = 10.244.0.0
    prefixlen = 16
    vxlan = 42
    vrf = 42

    [plan9]
    port = 8149

    [mdns]
    service = _9p2r._tcp.local.

    [topology]
    template = ""

  segment.dot: |
    digraph G {

        node [fillcolor="#ffffff", style=filled]

        subgraph cluster_v0 {
            label="$vrf_ifname";
            type=vrf;
            bgcolor="#f0f0f0";

            subgraph cluster_n0 {
                label="$namespace";
                type=netns;
                bgcolor="#c0c0c0";
                fd="$net_ns_fd";

                "port0" [type=interface, kind=veth, label="eth0", key=2];
                "port0" -> "port0:ip" [style=dashed, dir=none];
                "port0:ip" [
                    shape=note,
                    label="$veth_ipaddr",
                    fontsize=8,
                ];
            }

            "br0" [type=interface, kind=bridge, label="$br_ifname"];
            "br0" -> "br0:ip" [style=dashed, dir=none];
            "br0:ip" [
                shape=note,
                label="$br_ipaddr",
                fontsize=8,
            ];

            "port0" -> "br0";
        }

        "vxlan" [
            type=interface,
            kind=vxlan,
            label="$vxlan_ifname",
            vxlan_id=$vxlan_id,
            vxlan_group="239.1.1.1",
        ];
        "vxlan" -> "br0";
        "vxlan" -> "$host_ifname" [style=dashed, dir=none];
    }

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pyroute2-cni
  namespace: pyroute2-cni
  labels:
    tier: node
    app: pyroute2-cni
    k8s-app: pyroute2-cni
spec:
  selector:
    matchLabels:
      app: pyroute2-cni
  template:
    metadata:
      labels:
        tier: node
        app: pyroute2-cni
    spec:
      serviceAccountName: pyroute2-cni-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: pyroute2-cni
        image: ghcr.io/svinota/pyroute2-cni:0.0.287
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: host-root
          mountPath: /host
        - name: pyroute2-run
          mountPath: /var/run/pyroute2
        - name: server-config
          mountPath: /pyroute2-cni/config
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: pyroute2-run
        hostPath:
          path: /var/run/pyroute2
          type: DirectoryOrCreate
      - name: server-config
        configMap:
          name: server-config
