!
frr version 8.4_git
frr defaults traditional
hostname rr-01
no ipv6 forwarding
service integrated-vtysh-config
!
vrf vrf-200
 vni 50200
exit-vrf
!
router bgp 65000
 bgp router-id 192.168.124.1
 no bgp default ipv4-unicast
 neighbor FABRIC peer-group
 neighbor FABRIC remote-as 65000
 !
 ! add your node peers here:
 !
 neighbor 192.168.124.54 peer-group FABRIC
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC route-reflector-client
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
exit
!
router bgp 65000 vrf vrf-200
 !
 address-family ipv4 unicast
  redistribute kernel
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  route-target import 65000:200
  route-target export 65000:200
 exit-address-family
exit
!
end

