#!/usr/bin/env bash
set -euo pipefail

FRR_CONF=/etc/frr/frr.conf

read -r cmd
case "$cmd" in
  test)
    /usr/lib/frr/frr-reload.py --test /etc/frr/frr.conf
    echo "test: $?"
    ;;
  reload)
    /usr/lib/frr/frr-reload.py --reload /etc/frr/frr.conf
    echo "reload: $?"
    ;;
  *)
    echo ERR unknown command
    ;;
esac
